[package]
name = "unify"
version = "0.4.3"
entrypoint = "src/lib.typ"
authors = ["Christopher Hecker"]
repository = "https://github.com/ChHecker/unify"
license = "MIT"
description = "Format numbers, units, and ranges correctly."
exclude = ["README.md", "examples"]
