[package]
name = "qr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fast_qr = { git = "https://github.com/EpicEricEE/fast_qr", features = ["image", "svg"] }
wasm-minimal-protocol = { workspace = true }
