[package]
name = "qr"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Eric Biedert"]
license = "MIT"
description = "A QR Code generator."
repository = "https://github.com/EpicEricEE/typst-plugins"
compiler = "0.8.0"
exclude = ["README.md", "bin/**", "assets/**"]
