[package]
name = "dropcap"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Eric Biedert"]
repository = "https://github.com/EpicEricEE/typst-plugins"
license = "MIT"
description = "Customizable dropped capitals."
exclude = ["README.md", "assets"]
keywords = [
  "drop", "dropped", "big", "large", "caps", "capital", "capitals",
  "initial", "initials", "letter", "letters", "lettrine"
]
