[package]
name = "base64"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Eric Biedert"]
license = "MIT"
description = "Base64 encoding and decoding."
repository = "https://github.com/EpicEricEE/typst-plugins"
compiler = "0.8.0"
exclude = ["README.md", "assets/**"]
