[package]
name = "hash"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-minimal-protocol = { workspace = true }
blake2 = "0.10.6"
digest = "0.10.7"
md-5 = "0.10.5"
sha1 = "0.10.5"
sha2 = "0.10.7"
sha3 = "0.10.8"
